/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String topic;
    private String content;
    private String recipient;
    private String sender;

    public Message() {}

    public Message(Message value) {
        this.id = value.id;
        this.topic = value.topic;
        this.content = value.content;
        this.recipient = value.recipient;
        this.sender = value.sender;
    }

    public Message(
        Integer id,
        String topic,
        String content,
        String recipient,
        String sender
    ) {
        this.id = id;
        this.topic = topic;
        this.content = content;
        this.recipient = recipient;
        this.sender = sender;
    }

    /**
     * Getter for <code>socketprogrammingclientserver.message.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>socketprogrammingclientserver.message.id</code>.
     */
    public Message setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>socketprogrammingclientserver.message.topic</code>.
     */
    public String getTopic() {
        return this.topic;
    }

    /**
     * Setter for <code>socketprogrammingclientserver.message.topic</code>.
     */
    public Message setTopic(String topic) {
        this.topic = topic;
        return this;
    }

    /**
     * Getter for <code>socketprogrammingclientserver.message.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>socketprogrammingclientserver.message.content</code>.
     */
    public Message setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for <code>socketprogrammingclientserver.message.recipient</code>.
     */
    public String getRecipient() {
        return this.recipient;
    }

    /**
     * Setter for <code>socketprogrammingclientserver.message.recipient</code>.
     */
    public Message setRecipient(String recipient) {
        this.recipient = recipient;
        return this;
    }

    /**
     * Getter for <code>socketprogrammingclientserver.message.sender</code>.
     */
    public String getSender() {
        return this.sender;
    }

    /**
     * Setter for <code>socketprogrammingclientserver.message.sender</code>.
     */
    public Message setSender(String sender) {
        this.sender = sender;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Message other = (Message) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.topic == null) {
            if (other.topic != null)
                return false;
        }
        else if (!this.topic.equals(other.topic))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.recipient == null) {
            if (other.recipient != null)
                return false;
        }
        else if (!this.recipient.equals(other.recipient))
            return false;
        if (this.sender == null) {
            if (other.sender != null)
                return false;
        }
        else if (!this.sender.equals(other.sender))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.topic == null) ? 0 : this.topic.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.recipient == null) ? 0 : this.recipient.hashCode());
        result = prime * result + ((this.sender == null) ? 0 : this.sender.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(id);
        sb.append(", ").append(topic);
        sb.append(", ").append(content);
        sb.append(", ").append(recipient);
        sb.append(", ").append(sender);

        sb.append(")");
        return sb.toString();
    }
}
