/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.Message;
import database.tables.User;


/**
 * Convenience access to all tables in socketprogrammingclientserver.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>socketprogrammingclientserver.message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>socketprogrammingclientserver.user</code>.
     */
    public static final User USER = User.USER;
}
